Configuração do ESlint
UnBArqDsw2021-1/2021.1_G6_Curumim_Back-end pull request #22
Opened 2021-09-25 14:25 UTC by eliseukadesh67

## Descrição

Adiciona o ESlint ao projeto, para ajudar na padronização e controle de qualidade de código.

## Como testar

### 1. Instalar as dependências**

    yarn install

### 2. Adicionar configuração de "ActionOnSave" ao VScode**

Primeiro abra o settings.json, para fazer isso aperte Ctrl + Shift + p, e digite "settings", e clique em `Preferences: Open Settings (JSON)`

No arquivo `settings.json` do VScode adiciona o código abaixo.

     "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
      },
      "eslint.validate": [
        "javascript",
        "typescript"
      ],

### 3. Habilitar o ESlint

Aperte Ctrl + Shift + p e no console digite `ESLint: Manage Library Execution` e selecione a mesma opção

Após isso habilite a permissão do ESlint apertando em <strong>Allow<strong>

### 4. Abrir um arquivo javascript no projeto e ver o ESlint em ação!**

Exemplo:

![Screenshot from 2021-09-25 11-18-40](https://user-images.githubusercontent.com/48720096/134774693-ad082a14-01fc-4dbc-8803-ade83a0d4ec0.png)

Apertando Ctrl + S automaticamente o ESlint deverá resolver alguns problemas de indentação, adaptando ao padrão escolhido no arquivo `.eslintrc.json`, que no nosso caso foi usado o padrão `airbnb-base`.

2021-09-26 01:03 UTC, DanielPortods approved these changes
Aqui funcionou! 👍🏽

2021-09-26 02:07 UTC, edsondearaujo reviewed
![Captura de tela de 2021-09-25 19-59-07](https://user-images.githubusercontent.com/39536164/134790682-be9e8330-59a5-461d-8205-39417ed82f68.png)

- Estou recebendo um erro de permissão. Já tentei alguns comandos sudo chown -R ... mas não obtive sucesso.

2021-09-26 02:36 UTC, edsondearaujo commented
### OBS
- Recebi o erro de permissão porque não tinha executado o comando "sudo"  junto com o yarn install

2021-09-26 02:41 UTC, edsondearaujo approved these changes
Segui um caminho um pouco diferente das instruções. Mas no final deu certo. Funcionando certinho aqui também.  👍🏽

2021-09-27 12:25 UTC, omateusp requested changes
não queria instalar o yarn na minha máquina, seria interessante a opção de utilizar o mesmo dentro do docker.

2021-09-28 02:17 UTC, omateusp approved these changes

2021-09-28 02:17 UTC, merged