us04 e us08
UnBArqDsw2021-1/2021.1_G6_Curumim_Back-end pull request #26
Opened 2021-09-28 23:12 UTC by omateusp

# Como testar

Alterei algumas rotas então vou colocar todas as disponíveis aqui pra vcs testarem

## Sem autenticação:

### POST `/register-guardian`:
Registra um guardian e retorna informações, exemplo de body:
```json
{
    "name": "Nome da Pessoa", 
    "cpf": "12345678911", 
    "birthday": 31122021,
    "email": "example@email.com", 
    "password": "sua_senha",
    "adress": "um endereço qualquer"
}
```

### POST `/login`:
Faz login e retorna json com user e token, exemplo de body:
```json
{
    "email": "example@email.com", 
    "password": "sua_senha"
}
```

### POST `/dev/register-adm`:
*Rota temporária* Registra administrador.
```json
{
    "name": "Nome da Pessoa", 
    "cpf": "12345678911", 
    "birthday": 31122021,
    "email": "example@email.com", 
    "password": "sua_senha",
    "registration": 1
}
```

## Rotas autenticadas:
Para as rotas à seguir é necessário passar a token recebida no login pelos headers utilizando a key `Authorization`, as rotas `/adm` necessitam de uma token de adm, as `/teacher` de teacher e as `/guardian` de guardian.

### POST `/adm/register-teacher`:
Registra um professor.
```json
{
    "name": "Nome da Pessoa", 
    "cpf": "12345678911", 
    "birthday": 31122021,
    "email": "example@email.com", 
    "password": "sua_senha",
    "registration": 1
}
```

### POST `/adm/register-child`:
Registra uma criança
```json
{
    "name": "Nome da Pessoa", 
    "birthday": "2007-09-12",
    "registration": 1
}
```

### GET `/adm/list-guardians`:
Lista todos os guardians.

### GET `/adm/list-professionals`:
Lista todos os professionals.

### GET `/adm/list-activities`:
Lista todas as atividades.

### POST `/teacher/create-activity`:
Cria atividade.
```json
{
    "title": "eoq maluco, uma atividade", 
    "description": "atividade maluca", 
    "date": 31122021
}
```

### POST `/teacher/update-activity`:
Atualiza campos da atividade definidos no objeto updates.
```json
{
    "id": 15,
    "updates": {
        "title": "nome novo",
        "description": "faz"
    }
}
```

### POST `/teacher/delete-activity`: (talvez n devesse ser um post, sla)
Deleta atividade.
```json
{
    "id": 16
}
```

### GET `/teacher/list-activities`: 
Lista atividades do professor que fez a requisição.

### GET `/guardian/get-activity/:id`: 
Retorna informações da atividade pertencente ao id.

# Issues relacionadas

Close #20 
Close #13

2021-10-04 22:38 UTC, eliseukadesh67 reviewed
Rotas revisadas:

- POST /register-guardian: OK
- POST /login: OK

2021-10-04 23:09 UTC, eliseukadesh67 requested changes
A rota GET '/guardian/get-activity/:id' esta com erro.

2021-10-04 23:09 UTC, eliseukadesh67 commented on src/routes.js
> +routes.get('/guardian/get-activity', GuardianController.getActivityDetails);
Na rota `'/guardian/get-activity'` esta faltando o ":id" no final da rota, imagino que isso seja oq esta causando o erro na rota `GET '/guardian/get-activity/:id'`

2021-10-05 00:33 UTC, DanielPortods commented on src/routes.js
> +routes.get('/guardian/get-activity', GuardianController.getActivityDetails);
Acredito que pode ser desconsiderada essa rota visto que a regra de negocio para guardian acessar atividades seja através do board. Essa rota será excluida e trabalhada corretamente na issue #12 .

2021-10-05 02:05 UTC, eliseukadesh67 commented on src/routes.js
> +routes.get('/guardian/get-activity', GuardianController.getActivityDetails);
Ok. Ajustarei isso na #12.

2021-10-05 02:06 UTC, eliseukadesh67 approved these changes
Tudo certo!

2021-10-05 05:37 UTC, merged